version: '3.8'

services:
#  USER SERVICE
  postgres:
    image: postgres:15
    container_name: user-service-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chat-network

  redis:
    image: redis:latest
    container_name: redis_user
    ports:
      - "6379:6379"
    command: redis-server --requirepass demo
    volumes:
      - redis_data:/data
    networks:
      - chat-network

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address :9001
    volumes:
      - minio_data:/data
    networks:
      - chat-network
volumes:
  postgres_data:
  redis_data:
  minio_data:

networks:
  chat-network:
