server:
    port: 8080
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: api-gateway
#          uri: http://localhost:8081
#          predicates:
#            - Path=/
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka